workflows:
  ios-build-and-upload:
    name: iOS Build & Upload to App Store
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APPLE_ID: $APPLE_ID                     # Your Apple ID (set in Codemagic env)
        APP_SPECIFIC_PASSWORD: $APP_SPECIFIC_PASSWORD   # App-specific password (secret)
        DEVELOPMENT_TEAM: $DEVELOPMENT_TEAM     # Your Team ID, e.g., PDMPL563DB
      signing:
        ios:
          automatic: true
          team_id: $DEVELOPMENT_TEAM
    scripts:
      - name: Prepare Flutter
        script: |
          echo "🔹 Cleaning and fetching Flutter packages..."
          flutter clean
          flutter pub get

      - name: Fix iOS Deployment Target
        script: |
          echo "🔧 Setting iOS deployment target to 15.5..."
          sed -i.bak "s/platform :ios, '.*'/platform :ios, '15.5'/" ios/Podfile || true
          plutil -replace MinimumOSVersion -string "15.5" ios/Flutter/AppFrameworkInfo.plist
          sed -i.bak "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]\\+/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g" ios/Runner.xcodeproj/project.pbxproj || true

      - name: Install CocoaPods
        script: |
          echo "📦 Installing CocoaPods..."
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Archive iOS App
        script: |
          echo "📦 Archiving iOS app with automatic signing..."
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/ios/archive/Runner.xcarchive \
            clean archive

      - name: Export IPA
        script: |
          echo "📦 Exporting IPA..."
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ios/Runner/ExportOptions.plist \
            -exportPath build/ios/ipa

      - name: Upload IPA to App Store Connect
        script: |
          echo "🚀 Uploading IPA to App Store Connect..."
          xcrun altool --upload-app \
            -f build/ios/ipa/Runner.ipa \
            -t ios \
            -u $APPLE_ID \
            -p $APP_SPECIFIC_PASSWORD \
            --verbose

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
