workflows:
  ios-build:
    name: iOS Build (Automatic Signing)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Prepare Flutter
        script: |
          echo "🔹 Flutter version:"
          flutter --version
          flutter clean
          flutter pub get

      - name: Fix iOS Deployment Target
        script: |
          echo "🔧 Forcing iOS deployment target to 15.5..."

          # Podfile
          sed -i.bak "s/platform :ios, '.*'/platform :ios, '15.5'/" ios/Podfile || true

          # AppFrameworkInfo.plist
          plutil -replace MinimumOSVersion -string "15.5" ios/Flutter/AppFrameworkInfo.plist

          # project.pbxproj
          sed -i.bak "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]\\+/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g" ios/Runner.xcodeproj/project.pbxproj || true

      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Build iOS Archive
        script: |
          echo "🔹 Archiving iOS app with automatic signing..."
          # Build the archive
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/ios/archive/Runner.xcarchive \
            DEVELOPMENT_TEAM="PDMPL563DB" \
            CODE_SIGN_STYLE=Automatic \
            clean archive

          # Export IPA using ExportOptions.plist
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ios/Runner/ExportOptions.plist \
            -exportPath build/ios/ipa

    code_signing:
      ios:
        automatic_signing: true
        team_id: PDMPL563DB

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
