workflows:
  ios-build-and-upload:
    name: iOS Build & Upload to App Store
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APPLE_ID: $APPLE_ID
        APP_SPECIFIC_PASSWORD: $APP_SPECIFIC_PASSWORD
        DEVELOPMENT_TEAM: $DEVELOPMENT_TEAM
    scripts:
      - name: Prepare Flutter
        script: |
          flutter clean
          flutter pub get

      - name: Fix iOS Deployment Target
        script: |
          sed -i.bak "s/platform :ios, '.*'/platform :ios, '15.5'/" ios/Podfile || true
          plutil -replace MinimumOSVersion -string "15.5" ios/Flutter/AppFrameworkInfo.plist
          sed -i.bak "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]\\+/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g" ios/Runner.xcodeproj/project.pbxproj || true

      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Archive iOS App
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/ios/archive/Runner.xcarchive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE=Automatic \
            clean archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ios/Runner/ExportOptions.plist \
            -exportPath build/ios/ipa

      - name: Upload IPA to App Store Connect
        script: |
          xcrun altool --upload-app \
            -f build/ios/ipa/Runner.ipa \
            -t ios \
            -u $APPLE_ID \
            -p $APP_SPECIFIC_PASSWORD \
            --verbose

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
