workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Prepare Flutter
        script: |
          echo "🔹 Flutter version:"
          flutter --version
          flutter clean
          flutter pub get

      - name: Fix iOS Deployment Target
        script: |
          echo "🔧 Forcing iOS deployment target to 14.0..."

          # Podfile
          sed -i.bak "s/platform :ios, '.*'/platform :ios, '14.0'/" ios/Podfile || true

          # AppFrameworkInfo.plist
          plutil -replace MinimumOSVersion -string "14.0" ios/Flutter/AppFrameworkInfo.plist

          # project.pbxproj
          sed -i.bak "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]\+/IPHONEOS_DEPLOYMENT_TARGET = 14.0/g" ios/Runner.xcodeproj/project.pbxproj || true

      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
