workflows:
  ios-build-and-upload:
    name: iOS Build & Upload to App Store
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        DEVELOPMENT_TEAM: $DEVELOPMENT_TEAM
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY: $APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY

    scripts:
      - name: Prepare Flutter
        script: |
          echo "🔹 Cleaning and fetching Flutter packages..."
          flutter clean
          flutter pub get

      - name: Fix iOS Deployment Target
        script: |
          echo "🔧 Setting iOS deployment target to 15.5..."
          sed -i.bak "s/platform :ios, '.*'/platform :ios, '15.5'/" ios/Podfile || true
          plutil -replace MinimumOSVersion -string "15.5" ios/Flutter/AppFrameworkInfo.plist
          sed -i.bak "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]\\+/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g" ios/Runner.xcodeproj/project.pbxproj || true

      - name: Install CocoaPods
        script: |
          echo "📦 Installing CocoaPods..."
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Increment iOS Build Number
        script: |
          echo "🔢 Incrementing CFBundleVersion..."
          PLIST_PATH="ios/Runner/Info.plist"
          CURRENT_BUILD=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "$PLIST_PATH")
          if [ -z "$CURRENT_BUILD" ]; then
            CURRENT_BUILD=0
          fi
          NEW_BUILD=$((CURRENT_BUILD + 1))
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" "$PLIST_PATH"
          echo "CFBundleVersion updated from $CURRENT_BUILD to $NEW_BUILD"

      - name: Clean iOS build
        script: |
          echo "🧹 Cleaning iOS build..."
          cd ios
          xcodebuild clean -workspace Runner.xcworkspace -scheme Runner -configuration Release
          cd ..

      - name: Archive iOS App
        script: |
          echo "📦 Archiving iOS app with automatic signing..."
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/ios/archive/Runner.xcarchive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE=Automatic \
            ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=YES \
            clean archive

      - name: Export IPA
        script: |
          echo "📦 Exporting IPA..."
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ios/Runner/ExportOptions.plist \
            -exportPath build/ios/ipa

      - name: Verify SwiftSupport
        script: |
          echo "🔍 Checking SwiftSupport inside IPA..."
          cd build/ios/ipa
          unzip -q Runner.ipa -d ipa_contents
          if [ -d "ipa_contents/SwiftSupport" ]; then
            echo "✅ SwiftSupport folder found."
            echo "📂 SwiftSupport contents:"
            find ipa_contents/SwiftSupport -type f
          else
            echo "❌ SwiftSupport folder missing! Build will fail."
            exit 1
          fi
          cd ../../..

      - name: Upload IPA to App Store Connect
        script: |
          echo "🚀 Uploading IPA to App Store Connect via API key..."
          app-store-connect publish \
            --path build/ios/ipa/Runner.ipa \
            --key-id $APP_STORE_CONNECT_KEY_IDENTIFIER \
            --issuer-id $APP_STORE_CONNECT_ISSUER_ID \
            --private-key @env:APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY \
            --verbose

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - build/ios/ipa/*.dSYM.zip
