workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Prepare Flutter
        script: |
          echo "🔹 Flutter version:"
          flutter --version
          flutter clean
          flutter pub get

      - name: Fix iOS Deployment Target
        script: |
          echo "🔧 Forcing iOS deployment target to 15.5..."

          # Podfile
          sed -i.bak "s/platform :ios, '.*'/platform :ios, '15.5'/" ios/Podfile || true

          # AppFrameworkInfo.plist
          plutil -replace MinimumOSVersion -string "15.5" ios/Flutter/AppFrameworkInfo.plist

          # project.pbxproj
          sed -i.bak "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]\\+/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g" ios/Runner.xcodeproj/project.pbxproj || true

      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install
          cd ..
        vars:
        DEVELOPMENT_TEAM: $DEVELOPMENT_TEAM
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY: $APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY

      - name: Build Flutter iOS archive
        script: |
          flutter build ios --release --no-codesign
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/ios/archive/Runner.xcarchive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE=Automatic \
            clean archive

      - name: Upload IPA to App Store Connect
        script: |
          app-store-connect publish \
            --path build/ios/ipa/Runner.ipa \
            --key-id $APP_STORE_CONNECT_KEY_IDENTIFIER \
            --issuer-id $APP_STORE_CONNECT_ISSUER_ID \
            --private-key @env:APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY \
            --verbose

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - build/ios/ipa/*.dSYM.zip
