workflows:
  ios-build-and-upload:
    name: iOS Build & Upload to App Store
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        # Set these in Codemagic UI as secure variables
        DEVELOPMENT_TEAM: $DEVELOPMENT_TEAM
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY: $APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY

    scripts:
      - name: Prepare Flutter
        script: |
          echo "🔹 Cleaning Flutter and fetching packages..."
          flutter clean
          flutter pub get

      - name: Fix iOS Deployment Target
        script: |
          echo "🔧 Setting iOS deployment target to 15.5..."
          sed -i.bak "s/platform :ios, '.*'/platform :ios, '15.5'/" ios/Podfile || true
          plutil -replace MinimumOSVersion -string "15.5" ios/Flutter/AppFrameworkInfo.plist
          sed -i.bak "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g" ios/Runner.xcodeproj/project.pbxproj || true

      - name: Install CocoaPods
        script: |
          echo "📦 Installing CocoaPods..."
          cd ios
          rm -rf Pods Podfile.lock
          pod install --repo-update
          cd ..

      - name: Increment iOS Build Number
        script: |
          echo "🔢 Incrementing CFBundleVersion..."
          PLIST_PATH="ios/Runner/Info.plist"
          CURRENT_BUILD=${FLUTTER_BUILD_NUMBER:-0}
          NEW_BUILD=$((CURRENT_BUILD + 1))
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD" "$PLIST_PATH"
          echo "CFBundleVersion updated from $CURRENT_BUILD to $NEW_BUILD"

      - name: Archive iOS App (Automatic Signing)
        script: |
          echo "📦 Archiving app with automatic signing..."
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/ios/archive/Runner.xcarchive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE=Automatic \
            clean archive

      - name: Export IPA
        script: |
          echo "📦 Exporting IPA..."
          xcodebuild -exportArchive \
            -archivePath build/ios/archive/Runner.xcarchive \
            -exportOptionsPlist ios/Runner/ExportOptions.plist \
            -exportPath build/ios/ipa

      - name: Upload IPA to App Store Connect
        script: |
          echo "🚀 Uploading IPA to App Store Connect..."
          app-store-connect publish \
            --path build/ios/ipa/Runner.ipa \
            --key-id $APP_STORE_CONNECT_KEY_IDENTIFIER \
            --issuer-id $APP_STORE_CONNECT_ISSUER_ID \
            --private-key @env:APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY \
            --verbose

    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - build/ios/ipa/*.dSYM.zip
